using System.Collections.Generic;
using System.Runtime.InteropServices.JavaScript;

namespace bakalarka5.Core.Models;

public class TagSet
{
    public static List<string> TagSetNe =
    [
        "ah",
        "at",
        "az",
        "ge",
        "gh",
        "gl",
        "gm",
        "gq",
        "gp",
        "gr",
        "gs",
        "gt",
        "gu",
        "g_",
        "ia",
        "ic",
        "ig",
        "io",
        "m_",
        "me",
        "mi",
        "mn",
        "ms",
        "na",
        "nh",
        "ne",
        "nc",
        "ni",
        "nm",
        "no",
        "ns",
        "n_",
        "oa",
        "oe",
        "oi",
        "om",
        "op",
        "or",
        "os",
        "o_",
        "P ",
        "p1",
        "pc",
        "pd",
        "pf",
        "ph",
        "pn",
        "pm",
        "pp",
        "ps",
        "p_",
        "te",
        "td",
        "tf",
        "th",
        "tp",
        "ty",
        "t_"
    ];
}